# 2024.9.01下载的镜像
#FROM openjdk:11.0-jre-buster
# 设定时区
#ENV TZ=Asia/Shanghai
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 2024.9.02下载的镜像
FROM nacos/nacos-server:v2.1.0-slim
