git clone git@github.com:YFEYI/dockerimages.gitmkdir -vp dockerimages/hmall/Dockerfile <<'EOF'
FROM openjdk:11.0-jre-buster
LABEL MAINTAINER=master@yfeyi.top BUILDTYPE=Aliyun
EOFgit add . && git commit -m "nfs-subdir-external-provisioner" && git push
